[boris]
  version = 1

[build.dist-7-10-cli]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-cli"]
    ]

[build.dist-7-10-purescript]
  command = [
      ["master", "build", "dist-7-10", "-C", "loom-purescript"]
    ]

[build.branches-7-10-cli]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-cli"]
    ]

[build.branches-7-10-purescript]
  command = [
      ["master", "build", "branches-7-10", "-C", "loom-purescript"]
    ]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-rebased]
  command = [["rebased"]]

[build.all-submodules]
  command = [["dangling-refs"]]
