[boris]
  version = 1

[build.purescript-0-9-dist-7-10-core]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-core"]
    ]

[build.purescript-0-9-dist-7-10-build]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-build"]
    ]

[build.purescript-0-9-dist-7-10-cli]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-cli"]
    ]

[build.purescript-0-9-dist-7-10-config-toml]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-config-toml"]
    ]

[build.purescript-0-9-dist-7-10-fetch]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-fetch"]
    ]

[build.purescript-0-9-dist-7-10-machinator]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-machinator"]
    ]

[build.purescript-0-9-dist-7-10-http]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-http"]
    ]

[build.purescript-0-9-dist-7-10-js]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-js"]
    ]

[build.purescript-0-9-dist-7-10-process]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-process"]
    ]

[build.purescript-0-9-dist-7-10-projector]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-projector"]
    ]

[build.purescript-0-9-dist-7-10-sass]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-sass"]
    ]

[build.purescript-0-9-dist-7-10-site]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-site"]
    ]

[build.purescript-0-9-dist-7-10-runtime]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-runtime"]
    ]

[build.purescript-0-9-branches-7-10-core]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-core"]
    ]

[build.purescript-0-9-branches-7-10-build]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-build"]
    ]

[build.purescript-0-9-dist-7-10-purescript]
  command = [
      ["master", "build", "dist-7-10", "-C", "loom-purescript"]
    ]

[build.purescript-0-9-branches-7-10-cli]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-cli"]
    ]

[build.purescript-0-9-branches-7-10-config-toml]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-config-toml"]
    ]

[build.purescript-0-9-branches-7-10-fetch]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-fetch"]
    ]

[build.purescript-0-9-branches-7-10-machinator]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-machinator"]
    ]

[build.purescript-0-9-branches-7-10-http]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-http"]
    ]

[build.purescript-0-9-branches-7-10-js]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-js"]
    ]

[build.purescript-0-9-branches-7-10-process]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-process"]
    ]

[build.purescript-0-9-branches-7-10-projector]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-projector"]
    ]

[build.purescript-0-9-branches-7-10-sass]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-sass"]
    ]

[build.purescript-0-9-branches-7-10-site]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-site"]
    ]

[build.purescript-0-9-branches-7-10-runtime]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-runtime"]
    ]

[build.purescript-0-9-branches-7-10-purescript]
  command = [
      ["master", "build", "branches-7-10", "-C", "loom-purescript"]
    ]

[build.purescript-0-9-dist-8-0-core]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-core"]
    ]

[build.purescript-0-9-dist-8-0-build]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-build"]
    ]

[build.purescript-0-9-dist-8-0-cli]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-cli"]
    ]

[build.purescript-0-9-dist-8-0-config-toml]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-config-toml"]
    ]

[build.purescript-0-9-dist-8-0-fetch]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-fetch"]
    ]

[build.purescript-0-9-dist-8-0-machinator]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-machinator"]
    ]

[build.purescript-0-9-dist-8-0-http]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-http"]
    ]

[build.purescript-0-9-dist-8-0-js]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-js"]
    ]

[build.purescript-0-9-dist-8-0-process]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-process"]
    ]

[build.purescript-0-9-dist-8-0-projector]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-projector"]
    ]

[build.purescript-0-9-dist-8-0-sass]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-sass"]
    ]

[build.purescript-0-9-dist-8-0-site]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-site"]
    ]

[build.purescript-0-9-dist-8-0-runtime]
  command = [
      ["bin/master", "build", "dist-8-0", "-C", "loom-runtime"]
    ]

[build.purescript-0-9-branches-8-0-core]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-core"]
    ]

[build.purescript-0-9-branches-8-0-build]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-build"]
    ]

[build.purescript-0-9-dist-8-0-purescript]
  command = [
      ["master", "build", "dist-8-0", "-C", "loom-purescript"]
    ]

[build.purescript-0-9-branches-8-0-cli]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-cli"]
    ]

[build.purescript-0-9-branches-8-0-config-toml]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-config-toml"]
    ]

[build.purescript-0-9-branches-8-0-fetch]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-fetch"]
    ]

[build.purescript-0-9-branches-8-0-machinator]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-machinator"]
    ]

[build.purescript-0-9-branches-8-0-http]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-http"]
    ]

[build.purescript-0-9-branches-8-0-js]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-js"]
    ]

[build.purescript-0-9-branches-8-0-process]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-process"]
    ]

[build.purescript-0-9-branches-8-0-projector]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-projector"]
    ]

[build.purescript-0-9-branches-8-0-sass]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-sass"]
    ]

[build.purescript-0-9-branches-8-0-site]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-site"]
    ]

[build.purescript-0-9-branches-8-0-runtime]
  command = [
      ["bin/master", "build", "branches-8-0", "-C", "loom-runtime"]
    ]

[build.purescript-0-9-branches-8-0-purescript]
  command = [
      ["master", "build", "branches-8-0", "-C", "loom-purescript"]
    ]

[build.purescript-0-9-dist-validate]
  command = [["validate-respect"]]

[build.purescript-0-9-all-rebased]
  command = [["rebased"]]

[build.purescript-0-9-all-submodules]
  command = [["dangling-refs"]]
