[boris]
  version = 1

[build.dist-*]
  git = "refs/heads/master"

[build.branches-*]
  git = "refs/heads/topic/*"

[build.purescript-0-9-*]
  git = "refs/heads/purescript-0.9*"

[build.all-*]
  git = "refs/heads/**"
