[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20190103044641-3857bee/master-haskell-20190103044641-3857bee"
  version = 1
  sha1 = "c8396097bdf46fa16aae6660f8d1f3ea7a4bce72"

[global]
  CACHE = "true"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.2"
  PURESCRIPT_VERSION = "0.8.5.0"

[build.dist-7-10]
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "loom"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.2"

[build.dist-8-0]
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "loom"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.2"
  CACHE = "true"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.2"
